//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace throwaway.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("throwaway.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cert Details = .
        /// </summary>
        internal static string Cert_Details {
            get {
                return ResourceManager.GetString("Cert_Details", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cert Page gives 404 Error , we should still have been able to grab the Cert.
        /// </summary>
        internal static string Cert404StillGotCertMessage {
            get {
                return ResourceManager.GetString("Cert404StillGotCertMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Grab the Cert?.
        /// </summary>
        internal static string Grab_the_Cert_ {
            get {
                return ResourceManager.GetString("Grab_the_Cert_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to We appear to have got a null response from the webserver this usually means the URL is invalid or we were redirected to a non secure http:// only site.
        /// </summary>
        internal static string HttpstoHttpRedirectMessage {
            get {
                return ResourceManager.GetString("HttpstoHttpRedirectMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You must provide an https:// URL for the app to grab the cert.
        /// </summary>
        internal static string NonHttpsMessage {
            get {
                return ResourceManager.GetString("NonHttpsMessage", resourceCulture);
            }
        }
    }
}
